#!/bin/bash
PROFILE=$1
PATH_TO_MAIN_PROJECT=$2
COMMON_FOLDER=ERICnrcloudran
SOURCES_FOLDER_NAME=src
SOURCES_COMMON_FOLDER=../$COMMON_FOLDER/$SOURCES_FOLDER_NAME
TARGET_LINK_FOLDER=../build/$PROFILE

echo $PROFILE
echo $PATH_TO_MAIN_PROJECT
echo $COMMON_FOLDER
echo $SOURCES_FOLDER_NAME
echo $SOURCES_COMMON_FOLDER
echo $TARGET_LINK_FOLDER

if [ -e $SOURCES_FOLDER_NAME ]; then
   rm -rf $SOURCES_FOLDER_NAME
fi

ln -s $SOURCES_COMMON_FOLDER $SOURCES_FOLDER_NAME
exit 0
